import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import style from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <footer className={style.footer}>
          <div className={style.rodape}>
            <div>
              <p className={style.footerTitle}>FORMAS DE PAGAMENTO</p>
              <div className={style.footerIcons}>
                <img src="logopix.png" alt="PIX" />
              </div>
            </div>

            <div>
              <p className={style.footerTitle}>NÂO ENCONTROU O QUE PROCURAVA?<br />FALE CONOSCO.</p>
              <div className={style.footerIcons}>
                <img src="logowhatsapp.png" alt="" />
                <p><strong>(83) 987375521</strong></p>
                <p><strong>(83) 987680837</strong></p>
              </div>
            </div>

            <div>
              <p className={style.footerTitle}>SIGAM NOSSO INSTAGRAM</p>
              <div className={style.footerIcons}>
                <img src="logoinstagram.png" alt="Instagram" />
                <span>@jg.modass18</span>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
